### ISSUE TITLE
Import error on Python 3.9.5

### ISSUE THREAD

**Issue by parkerlreed** [flok/pydualsense#27]
Arch Linux

```
Python 3.9.5 (default, May 24 2021, 12:50:35) 
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pydualsense import pydualsense, TriggerModes
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/cffi/cparser.py", line 336, in _parse
    ast = _get_parser().parse(fullcsource)
  File "/usr/lib/python3.9/site-packages/pycparser/c_parser.py", line 149, in parse
    return self.cparser.parse(
  File "/usr/lib/python3.9/site-packages/pycparser/ply/yacc.py", line 331, in parse
    return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
  File "/usr/lib/python3.9/site-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "/usr/lib/python3.9/site-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
    r = errorfunc(token)
  File "/usr/lib/python3.9/site-packages/pycparser/c_parser.py", line 1858, in p_error
    self._parse_error(
  File "/usr/lib/python3.9/site-packages/pycparser/plyparser.py", line 67, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: <cdef source string>:4:5: before: ULONG_PTR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/pydualsense/__init__.py", line 2, in <module>
    from .pydualsense import pydualsense, DSLight, DSState, DSTouchpad, DSTrigger, DSAudio
  File "/usr/lib/python3.9/site-packages/pydualsense/pydualsense.py", line 7, in <module>
    import hidapi
  File "/usr/lib/python3.9/site-packages/hidapi.py", line 4, in <module>
    ffi.cdef("""
  File "/usr/lib/python3.9/site-packages/cffi/api.py", line 112, in cdef
    self._cdef(csource, override=override, packed=packed, pack=pack)
  File "/usr/lib/python3.9/site-packages/cffi/api.py", line 126, in _cdef
    self._parser.parse(csource, override=override, **options)
  File "/usr/lib/python3.9/site-packages/cffi/cparser.py", line 389, in parse
    self._internal_parse(csource)
  File "/usr/lib/python3.9/site-packages/cffi/cparser.py", line 394, in _internal_parse
    ast, macros, csource = self._parse(csource)
  File "/usr/lib/python3.9/site-packages/cffi/cparser.py", line 338, in _parse
    self.convert_pycparser_error(e, csource)
  File "/usr/lib/python3.9/site-packages/cffi/cparser.py", line 367, in convert_pycparser_error
    raise CDefError(msg)
cffi.CDefError: cannot parse "ULONG_PTR Internal;"
<cdef source string>:4:5: before: ULONG_PTR
```

**Comment by parkerlreed** [comment]
Closing as https://github.com/flok/pydualsense/issues/22 is the same
