### ISSUE TITLE
Failure on macOS, M1

### ISSUE THREAD

**Issue by UEFI-code** [flok/pydualsense#40]
I'm trying on my M1 Mac, and got error out of index. I guess some hid data were missing
```
Python 3.10.8 (main, Oct 13 2022, 09:48:40) [Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pydualsense
>>> obj = pydualsense.pydualsense()
>>> obj.init()
>>> Exception in thread Thread-1 (sendReport):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/pydualsense/pydualsense.py", line 216, in sendReport
    self.readInput(inReport)
  File "/opt/homebrew/lib/python3.10/site-packages/pydualsense/pydualsense.py", line 262, in readInput
    misc2 = states[10]
IndexError: list index out of range

>>> obj.device.get_product_string()
'DualSense Wireless Controller'
>>> data = obj.device.read(64)
>>> data
b'\x01\x80~\x7f~\x08\x00\x08\x00\x00'
```

**Comment by flok** [comment]
I dont have an arm device to test. but it seems like the hidapi works diffrent in the m1.

how did you install the hidapi?

**Comment by UEFI-code** [comment]
I use the “brew install hidapi” directly

------------------ Original ------------------
From: Flo ***@***.***&gt;
Date: Tue,Jan 10,2023 10:55 PM
To: flok/pydualsense ***@***.***&gt;
Cc: SuperHacker UEFI ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [flok/pydualsense] Failure on macOS, M1 (Issue #40)





 
I dont have an arm device to test. but it seems like the hidapi works diffrent in the m1.
 
how did you install the hidapi?

**Comment by flok** [comment]
This is weird. Could you change the source and output the states list with a print ?

**Comment by UEFI-code** [comment]
I think I set the verbose to True it will print something.
```
>>> import pydualsense
>>> obj = pydualsense.pydualsense(True)
>>> obj.init()
>>> 2023-01-19 11:00:42,754 b'\x01\x7f~\x80\x80\x08\x00\x00\x00\x00'
Exception in thread Thread-1 (sendReport):
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/pydualsense/pydualsense.py", line 216, in sendReport
    self.readInput(inReport)
  File "/opt/homebrew/lib/python3.10/site-packages/pydualsense/pydualsense.py", line 268, in readInput
    self.state.trackPadTouch0.ID = inReport[33] & 0x7F
IndexError: index out of range
```
Hidapi on m1 output data less then other platform

**Comment by rongweiji** [comment]
Hi thank you for this issue . and also thank flok's great repo.   I have tried this lib on my m3 device , it does not work , i find out the hidapi wont works well on the mac device ( hidapi_usb ) . 
will raise the erro in the hidapi.py : 
    raise OSError('System platform not supported')
 is there any possible to replace other hidapi library to be suitable with the mac device  ?

**Comment by flok** [comment]
It's seems that the arm chips of apple are recognized in python by a different platform (which makes sense). I have not implemented this platform type yet.

As i don't have a mac arm device on hand my support is limited.
Pydualsense uses a modified hidapi python binding using cffi. You can find that here: https://github.com/flok/hidapi-cffi

First approach would be to test what the sys.platform prints out on mac arm chips and then implement that platform inside the hidapi.py in here: https://github.com/flok/hidapi-cffi/blob/master/hidapi.py#L5 (maybe no c code changes are required and only another or parameter for the linux / darwin branch is needed.

If someone can test this on their machine and create PR i will gladly merge it and release a new version

**Comment by rongweiji** [comment]
> It's seems that the arm chips of apple are recognized in python by a different platform (which makes sense). I have not implemented this platform type yet.
> 
> As i don't have a mac arm device on hand my support is limited. Pydualsense uses a modified hidapi python binding using cffi. You can find that here: https://github.com/flok/hidapi-cffi
> 
> First approach would be to test what the sys.platform prints out on mac arm chips and then implement that platform inside the hidapi.py in here: https://github.com/flok/hidapi-cffi/blob/master/hidapi.py#L5 (maybe no c code changes are required and only another or parameter for the linux / darwin branch is needed.
> 
> If someone can test this on their machine and create PR i will gladly merge it and release a new version

thank you for your reply , you did greate work on this repo , and i will tried a minumun adjust to make it works on mac device later. When I complete the implement. i will let you know .

**Comment by UEFI-code** [comment]
Maybe we need a study about HID device interaction method on MacOS

(I hypotheses newer macOS already intergrated dualsense driver officially including both USB and Bluetooth, so you can use dualsense to control some sys UI directly. Maybe there is a more special way to interact with dualsense on macOS rather than general HID method…)

By the way, I was use ```os.uname().sysname == "Darwin"``` to recognize macOS, I didn't tested ```os.name``` on M1 macOS...

I first created this issue 2 years ago, many 3rd part lib might be changed a lot...

**Comment by rongweiji** [comment]
> > It's seems that the arm chips of apple are recognized in python by a different platform (which makes sense). I have not implemented this platform type yet.
> > As i don't have a mac arm device on hand my support is limited. Pydualsense uses a modified hidapi python binding using cffi. You can find that here: https://github.com/flok/hidapi-cffi
> > First approach would be to test what the sys.platform prints out on mac arm chips and then implement that platform inside the hidapi.py in here: https://github.com/flok/hidapi-cffi/blob/master/hidapi.py#L5 (maybe no c code changes are required and only another or parameter for the linux / darwin branch is needed.
> > If someone can test this on their machine and create PR i will gladly merge it and release a new version
> 
> thank you for your reply , you did greate work on this repo , and i will tried a minumun adjust to make it works on mac device later. When I complete the implement. i will let you know .

after i have tried the adjustement in the hidapi.py. which is dependency 

```if platform.startswith('linux') or platform.startswith('darwin'):```  this code will works for fixing my issue , and i have tred several hid features it's stable , 
my deivce Macbook AIR 2024 M3. I think i will create the pr top on that library after I do more stable monitoring.

**Comment by rongweiji** [comment]
i noticed that in  https://github.com/flok/hidapi-cffi , there is. the adjustment for support the macos , but it did not appear in this  library, i am not sure what the step i should take .

**Comment by flok** [comment]
> i noticed that in https://github.com/flok/hidapi-cffi , there is. the adjustment for support the macos , but it did not appear in this library, i am not sure what the step i should take .

Thanks for the info. Seems like i received a PR several years ago but didn't create a new pypi release for it.

I just created it and will also update the dependency inside pydualsense. After this it should also work on apple silicon pc.

**Comment by flok** [comment]
v0.7.3 with the hidapi-cffi changed is release. could you test it please?

**Comment by rongweiji** [comment]
> v0.7.3 with the hidapi-cffi changed is release. could you test it please?

Thank you. Now it works , i have tried several function in my own project include: 
- HID api connection features , read and write command 
- UAC , playback on the haptic motors

There is still a limitation in macos, I believe it's the system drive issue , I can not playback on the speaker of the controller.  The system wont detect the speaker's channel


- My device: Macbook Air 2024 M3 Chip

**Comment by AntoineGR** [comment]
Hello, following these updates I am also trying to use on Apple Silicon (Macbook M2), but getting this error :
```python
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/hidapi.py", line 154, in <module>
    raise OSError("Could not find any hidapi library")
OSError: Could not find any hidapi library
``` 

My installation process :

1. `brew install hidapi`
which installed successfully `hidapi--0.14.0.arm64_ventura.bottle.tar.gz`

2. `pip3 install pydualsense`
which `Successfully installed cffi-1.17.1 hidapi-usb-0.3.2 pydualsense-0.7.3`

@wayne-xyz Did you do anything else to make it work ?

**Comment by AntoineGR** [comment]
I just solved the issue by adding a path to hidapi.py (l.135) :
```python
library_paths = (
    '/opt/homebrew/lib/libhidapi.dylib',
    ...
``` 
The problem came from the fact that `ffi.dlopen(lib)` (l.150) does _not_ search in `/opt/homebrew/lib/`, which is the default Homebrew install folder on Apple Silicon.
Not sure what's the most elegant way to solve that dynamically though...

**Comment by flok** [comment]
> /opt/homebrew/lib/libhidapi.dylib

That should work out of the box in the /opt/homebrew/lib is inside the environment variables as ffi uses them as far as i'm aware.

**Comment by ideoforms** [comment]
I ran into the same thing. To solve more elegantly:

- If Python has been installed via `homebrew`, you can set the environmental var `export DYLD_LIBRARY_PATH=/opt/homebrew/lib:$DYLD_LIBRARY_PATH` to inform Python where to find the library
- However, if Python has been installed from a python.org installer or is using the system Python, this **will not work** as System Integrity Protection strips out so that `dlopen()` does not receive it. 

Unfortunately, this means that there's no real elegant solution for these types of Python install. Aside from patching hidapi.py, this is probably the least-bad option:

```
sudo mkdir -p /usr/local/lib
sudo ln -s /opt/homebrew/lib/libhidapi.dylib /usr/local/lib/libhidapi.dylib
```
