### ISSUE TITLE
Bluetooth connection

### ISSUE THREAD

**Issue by mwlock** [flok/pydualsense#49]
I am trying to connect my controller via Bluetooth. I am using Ubuntu 18.04

I noticed that the report size is only 10, therefore the code is throwing an error when running

```
Report length 10
Device connected via bluetooth
[INFO] [1683724328.458037]: Connected to controller.
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jfine/.local/lib/python3.6/site-packages/pydualsense/pydualsense.py", line 233, in sendReport
    self.readInput(inReport)
  File "/home/jfine/.local/lib/python3.6/site-packages/pydualsense/pydualsense.py", line 287, in readInput
    misc2 = states[10]
IndexError: list index out of range
```

**Comment by dieterdejonghe** [comment]
Same issue more or less for me, connected on BT on ubuntu JEtson nano if that makes a difference.

debug print gave me a 10 as wel for the Report length
 
File "/home/jetson/.local/lib/python3.10/site-packages/pydualsense/pydualsense.py", line 232, in sendReport
    inReport = self.device.read(self.input_report_length)
AttributeError: 'pydualsense' object has no attribute 'input_report_length'
